[versions]
kotlin = "2.0.0"
wrappers-kotlin-js = "2026.1.10"
wrappers-kotlin-node = "2026.1.10-24.10.4"
ktlint = "0.9.0"
seskar = "3.6.0"
karakum = "1.0.0-alpha.46"
maven-publish = "0.29.0"
jnpm = "1.6"

[libraries]
kotlin-wrappers-js = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-js", version.ref = "wrappers-kotlin-js" }
kotlin-wrappers-node = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-node", version.ref = "wrappers-kotlin-node" }
jnpm = { group = "org.orienteer.jnpm", name = "jnpm", version.ref = "jnpm" }

# Gradle
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-plugin = { group = "io.github.usefulness", name = "ktlint-gradle-plugin", version.ref = "ktlint" }
seskar-plugin = { group = "io.github.turansky.seskar", name = "seskar-gradle-plugin", version.ref = "seskar" }
karakum-plugin = { group = "io.github.sgrishchenko", name = "karakum-gradle-plugin", version.ref = "karakum" }
maven-publish-plugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
